### ISSUE TITLE
CLI - Incorrect error message for Organization Type 

### ISSUE THREAD

**Issue by Patrick-Erichsen** [target/consensource#19]
# Report

The error message for invalid organization types on the CLI is incomplete.

## Description

When entering an invalid organization type in the CLI (e.g. `creg organization create "Test Factory" "5" "Test User" "012-345-6789" "EN"`), the resulting error message is incomplete. 

Currently it reads `Invalid organization type: {:?}. It can be 1 for CERTIFYING_BODY or 2 for STANDARDS_BODY`. This doesn't include the 3rd organization type, `3 for FACTORY`.

**Comment by Patrick-Erichsen** [comment]
Working on #18 and noticed this. Thought I'd create a separate issue to track the work.

**Comment by Patrick-Erichsen** [comment]
Submitted PR #20

**Comment by adeebahmed** [comment]
Resolved in #20
