### ISSUE TITLE
Upgrade Rocket 0.3 -> 0.4 🚀 

### ISSUE THREAD

**Issue by adeebahmed** [target/consensource#2]
Updating crates.io index
    Updating git repository `https://github.com/peterschwarz/hyper-sse.git`
error: failed to select a version for the requirement `ring = "^0.11.0"`
  candidate versions found which didn't match: 0.14.6, 0.14.5, 0.14.4, ...
  location searched: crates.io index
required by package `cookie v0.9.1`
    ... which is depended on by `rocket v0.3.0`
    ... which is depended on by `rocket_codegen v0.3.0`
    ... which is depended on by `cert-registry-rest-api v0.1.0 (/consensource/rest_api)`

**Comment by rahealy** [comment]
This seems to be related to the ring author yanking old releases by policy thus breaking out of date dependencies for many packages:

https://github.com/briansmith/ring/issues/774

Came here from Target job posting - want to play with what you folks are working on.

**Comment by adeebahmed** [comment]
Thanks for the insight @rahealy glad you were able to find the repo. 
Feel free to clone and mess around with it 😄

**Comment by ajaya-man** [comment]
I am not able to find the solution. Can you help me to solve the error above? What changes should I make. I am new to rust projects.

**Comment by sharma66mahesh** [comment]
I read about this project from here: https://www.coindesk.com/retail-giant-target-is-working-on-a-blockchain-for-supply-chains
However, I am stuck at this same error. What changes should I make in this project to resolve this error?

**Comment by adeebahmed** [comment]
@ajaya-man @sharma66mahesh Since the author of `ring` yanked the version of the `ring` crate that the `rocket 0.3.0` rest-api depended on, you can no longer build it manually. You can however run a docker-compose up, and it will pull precompiled images from dockerhub so you can at least run ConsenSource.

Since the author has decided to remove older versions of `ring` from crates there's nothing we can do to make it compile. Aside from finding that specific version of ring and force feeding it to the app. 

The appropriate solution would be to `upgrade rocket from 0.3 -> 0.4`

**Comment by adeebahmed** [comment]
Upgrade started here: #12

Feel free to finish it off 😄 

@ajaya-man @sharma66mahesh, if either of you take this on, it'd be a good way for you to learn about rust!

**Comment by pa3ng** [comment]
PR #12 closed in favor of #13

**Comment by pa3ng** [comment]
PR #13 closed in favor of #15

**Comment by adeebahmed** [comment]
Merged #16
