### ISSUE TITLE
E0658 Error on CLI Container Build

### ISSUE THREAD

**Issue by crawfordleeds** [target/consensource#21]
# Report

I'm having issues building a container for the CLI. Specifically, compilation of getrandom v0.1.6 fails with error E0658 (run `rustc --explain E0658` for more details).

## Description

I started by cloning the repo directly - HEAD is at commit [90f63ff](https://github.com/target/consensource/commit/90f63ff57bb4ad5284748446b5e7af5f38f121c7). From there I ran `docker-compose -f docker-compose.yaml up`, per the instructions in the root README.

This resulted in a few errors with Error code E0658 (see screenshot for details). I tried to isolate the issue by cd'ing into consensource/cli and running `docker build ${PWD}`. While this replicated the issue, it didn't give me much insight for a fix.

It's not clear if this is important, but when the build starts, I'm receiving a warning that says:
```
warning: unused manifest key: bin.0.cargo-features
```

This isn't something I've seen before. I found a few forum comments that suggested this was an issue with an old version of cargo but that doesn't seem to be the case. However, I am suspicious this is leading to an issue. If I try to run `build cargo` instead of building the docker image, I get the following error:

```
error: unable to get packages from source

Caused by:
     failed to parse manifest at '/Users/crawfordleeds/.cargo/registry/src/github.com1ecc6299db9ec823/rand-0.7.0/Cargo.toml'
```

This seems to be an issue with reading the Cargo.toml file.

Note, I recently re-installed rust through the instructions on [rustup.rs](https://rustup.rs/) which currently installs rustc stable-1.36.0. I changed my local machine to `rustc 1.31.0-nightly (1cf82fd9c 2018-10-30)` per the [official instructions](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/rustup-for-managing-rust-versions.html). In summary, I ran `rustup install nightly-2018-10-31` and `rustup default nightly-2018-10-31`. Note, 10-31 is intentional. This actually results in a hash to match what is currently in the root README, 1cf82fd9c. 10-30 installs 10-29 for some reason, at least it does with the darwin toolchain.

It's unclear to me if this is somehow a problem with my machine. I'm happy to dig a bit deeper on my own, but I thought I'd first check if this appears obvious to anyone else. Thanks!

## Screenshots

Here is a screenshot of the error after running `docker-compose -f docker-compose.yaml up`. The result is virtually identical when running `docker build ${PWD}` from consensource/cli. 

![Screen Shot 0](https://user-images.githubusercontent.com/25166339/61166759-48ae4e80-a4f0-11e9-948c-207a3f53fd18.png)

Here is a screenshot of the error after running `cargo build` from the consensource/cli directory.
![Screen Shot 1](https://user-images.githubusercontent.com/25166339/61167078-3f27e500-a4f6-11e9-909b-0ddf308760a3.png)

## Your Environment

Please complete the following information):
 - OS: `macOS`
 - OS version: `10.14.5`
 - Rustc version: `rustc 1.31.0-nightly (1cf82fd9c 2018-10-30)`

## Additional Context
Note, I am running the most up to date version of Docker, version 2.0.0.3.

**Comment by adeebahmed** [comment]
I have built the cli successfully with different versions of the stable toolchain. 
Note that only the rest-api requires nightly. Try with stable.

I will update the top-level README to clarify this to avoid future confusion. Thanks for bringing this to our attention 😄

**Comment by crawfordleeds** [comment]
Thanks, @adeebahmed, unfortunately, I'm still getting an issue with the CLI no matter what version of rustc I use. Okay, I haven't tried them all just 4 or 5 ranging from 1.30.0 to 1.38.0. Using docker-compose, I continue to get the E0658 Error. If I move into the /cli directory and run `cargo build`, I get a different error. Traceback below:

```
Crawfords-MacBook-Pro-830:cli crawfordleeds$ RUST_BACKTRACE=1 cargo build
warning: unused manifest key: bin.0.cargo-features
   Compiling zmq-sys v0.8.3
   Compiling protobuf-codegen v2.7.0
   Compiling openssl v0.10.23
   Compiling openssl-sys v0.9.47
   Compiling serde_yaml v0.8.9
error: failed to run custom build command for `zmq-sys v0.8.3`

Caused by:
  process didn't exit successfully: `/Users/crawfordleeds/Documents/repos/target/consensource/cli/target/debug/build/zmq-sys-f50fd59974a7b901/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to locate libzmq:
Failed to run `"pkg-config" "--libs" "--cflags" "libzmq >= 3.2"`: No such file or directory (os error 2)', /Users/crawfordleeds/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-sys-0.8.3/build.rs:31:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:336
   7: build_script_build::main
             at ./build.rs:31
   8: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  11: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  12: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  13: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I noticed that you gitignore all Cargo.lock files. The [Cargo Book](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) recommends including the Cargo.lock file if compiling to binaries.

Is it possible I'm having issues due to different lock files? Here's mine for reference: 
[Cargo.lock.zip](https://github.com/target/consensource/files/3408178/Cargo.lock.zip)

Thanks!

**Comment by adeebahmed** [comment]
Sure, I've included the .lock files in the repo as this is the recommended practice. 
(https://github.com/target/consensource/pull/23)

**Comment by crawfordleeds** [comment]
Thanks, @adeebahmed. I'm still having trouble but now it really sounds like an issue on my end. Will report back if I resolve the issue in case anyone else has the same challenge in the future.

**Comment by crawfordleeds** [comment]
In case anyone else runs into this issue in the future, I have solved the problem with building the CLI with `cargo build`, not docker.

I had two issues: I didn't have pkg-config installed or libzmq. This was easily fixed with homebrew: `brew install pkg-config` and `brew install libzmq`.

@adeebahmed would you find it useful to document this in any of the README's? Happy to make a PR if you'd like to see that added.

I'm still having the issues with building using docker. Logs below:

```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/error_impls.rs:13:5
   |
8  | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
13 | use std::{error, io};
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/error_impls.rs:8:1
   |
8  | extern crate std;
   | ^^^^^^^^^^^^^^^^^

error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/use_file.rs:15:5
   |
10 | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
15 | use std::{fs::File, io::Read};
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/use_file.rs:10:1
   |
10 | extern crate std;
   | ^^^^^^^^^^^^^^^^^

error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/linux_android.rs:15:5
   |
10 | extern crate std;
   | ----------------- not an extern crate passed with `--extern`
...
15 | use std::io;
   |     ^^^
   |
note: this import refers to the extern crate imported here
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.6/src/linux_android.rs:10:1
   |
10 | extern crate std;
   | ^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `getrandom`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by adeebahmed** [comment]
Probably be best to add those install steps to the cli docs. Thanks for taking the time figuring out the problem. Your error indicates that rust nightly is being used to build, where stable is required. 


The proper way to build this would be with `docker-compose` 

`docker-compose up --build` - builds all images
 `docker-compose up -d --build cli` - build a specific image

**Comment by crawfordleeds** [comment]
In regards to the rust nightly vs. stable error - that's what I thought. However, I don't get the same error if I build locally with `cargo build` using nightly. Isn't this set by the docker container? Changing my local version of rustc doesn't seem to impact the error in the docker build.

**Comment by pa3ng** [comment]
hi @crawfordleeds there's a new version of `target/consensource:build_agent` which should resolve the `E0658` error upon compilation. Although, you might run into this new issue subsequently #24

**Comment by crawfordleeds** [comment]
Thanks, @pa3ng! I'll take a look shortly.
